name: Parallel Cypress Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run cypress
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        machines: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          parallel: true
          group: "Running tests"
          start: yarn start
          wait-on: http://localhost:3000
        env:
          CI: true
